/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  sdkSidebar: [
    'sdks/index',
    'sdks/architecture/index',
    {
      type: 'category',
      label: 'Prerequisites',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'sdks/sdk-keys',
          className: 'sidebar-icon sidebar-icon--one'
        },
        {
          type: 'doc',
          id: 'sdks/event-logging',
          className: 'sidebar-icon sidebar-icon--two'
        }
      ]
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      collapsible: false,
      collapsed: false,
      items: [
        'sdks/common-issues',
        'sdks/faqs',
      ]
    },
    {
      type: 'category',
      label: 'Client SDKs',
      collapsible: false,
      collapsed: false,
      items: [
        'sdks/client-sdks/index',
        {
          type: 'doc',
          id: 'sdks/client-sdks/ios',
          className: 'sidebar-icon sidebar-icon--ios'
        },
        {
          type: 'doc',
          id: 'sdks/client-sdks/android',
          className: 'sidebar-icon sidebar-icon--android'
        },
        {
          type: 'doc',
          id: 'sdks/client-sdks/javascript',
          className: 'sidebar-icon sidebar-icon--js'
        },
        {
          type: 'doc',
          id: 'sdks/client-sdks/react-native',
          className: 'sidebar-icon sidebar-icon--reactnative'
        }
      ]
    },
    {
      type: 'category',
      label: 'Server SDKs',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'sdks/server-sdks',
        }
      ]
    },
    {
      type: 'category',
      label: 'Features',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'sdks/sdk-features'
        }
      ]
    },
    
  ],

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: false,
      collapsed: false,
      items: [
        { 
          type: 'doc',
          label: 'About Eppo',
          id: 'home'
        },
        {
          type: 'category',
          label: 'Quickstart Guides',
          items: [
            {
              type: 'autogenerated',
              dirName: 'quick-starts',
            }
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Flag and Experiment Configuration',
          items: [
            {
              type: 'autogenerated',
              dirName: 'feature-flagging',
            }
          ]
        },
        {
          type: 'category',
          label: 'Data Management',
          items: [
            {
              type: 'autogenerated',
              dirName: 'data-management',
            }
          ]
        },
        {
          type: 'category',
          label: 'Experiment Analysis',
          items: [
            {
              type: 'autogenerated',
              dirName: 'experiment-analysis',
            }
          ]
        },
        {
          type: 'category',
          label: 'Contextual Bandits',
          items: [
            {
              type: 'autogenerated',
              dirName: 'contextual-bandits',
            }
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Guides',
          items: [
            {
              type: 'autogenerated',
              dirName: 'guides',
            }
          ]
        },
        {
          type: 'category',
          label: 'Statistics',
          items: [
            {
              type: 'autogenerated',
              dirName: 'statistics',
            }
          ]
        },
        {
          type: 'category',
          label: 'Administration',
          items: [
            {
              type: 'autogenerated',
              dirName: 'administration',
            }
          ]
        },
        {
          type: 'doc',
          label: 'REST API',
          id: 'reference/api/index'
        },
        {
          type: 'doc',
          label: 'Webhooks',
          id: 'reference/webhook'
        },
      ]
    },
  ],
  
  
};

module.exports = sidebars;
