/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: false,
      collapsed: false,
      items: [
        { 
          type: 'doc',
          label: 'About Eppo',
          id: 'home'
        },
        {
          type: 'category',
          label: 'Quickstart Guides',
          items: [
            {
              type: 'autogenerated',
              dirName: 'quick-starts',
            }
          ]
        },
      ]
    },
    {
      type: 'category',
      label: 'Core Concepts',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Flag and Experiment Configuration',
          items: [
            {
              type: 'autogenerated',
              dirName: 'feature-flagging',
            }
          ]
        },
        {
          type: 'category',
          label: 'Data Management',
          items: [
            {
              type: 'autogenerated',
              dirName: 'data-management',
            }
          ]
        },
        {
          type: 'category',
          label: 'Experiment Analysis',
          items: [
            {
              type: 'autogenerated',
              dirName: 'experiment-analysis',
            }
          ]
        },
        {
          type: 'category',
          label: 'Geolift (Quasi-experiments)',
          items: [
            {
              type: 'autogenerated',
              dirName: 'geolift',
            }
          ]
        },
        {
          type: 'category',
          label: 'Contextual Bandits',
          items: [
            {
              type: 'autogenerated',
              dirName: 'contextual-bandits',
            }
          ]
        }
      ]
    },
    {
      type: 'category',
      label: 'SDKs',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'sdks',
        }
      ]
    },
    {
      type: 'category',
      label: 'Guides',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides',
        }
      ]
    },
    {
      type: 'category',
      label: 'Reference',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Statistics',
          items: [
            {
              type: 'autogenerated',
              dirName: 'statistics',
            }
          ]
        },
        {
          type: 'category',
          label: 'Administration',
          items: [
            {
              type: 'autogenerated',
              dirName: 'administration',
            }
          ]
        },
        {
          type: 'doc',
          label: 'REST API',
          id: 'reference/api/index'
        },
        {
          type: 'doc',
          label: 'Webhooks',
          id: 'reference/webhook'
        },
        {
          type: 'doc',
          label: 'Architecture and Security',
          id: 'reference/architecture-and-security'
        },
      ]
    },
  ],
  
  
};

module.exports = sidebars;
